name: "Terraform module CI"

# note:
#   for this workflow to work from a new repo in the organization the following must be done:
#     - allow the repo access to the organization secret ORG_TF_CICD_APP_PRIVATE_KEY here: https://github.com/organizations/dsb-norge/settings/secrets/actions
#     - allow the repo access to the organization variables ORG_TF_CICD_APP_ID and ORG_TF_CICD_APP_INSTALLATION_ID here: https://github.com/organizations/dsb-norge/settings/variables/actions
#     - allow the app 'dsb-norge-terraform-cicd-access' access to this repo by "configuring" the app from here: https://github.com/organizations/dsb-norge/settings/installations

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

  # allows manual build
  workflow_dispatch:

  # we want this workflow to run when release PR's are created
  #   since these PR's are created by actions they do not raise the pull_request event
  workflow_run:
    workflows: ["Tag and release terraform module"]
    types: [completed]
    branches: [main]

env:
  ARM_TENANT_ID: ${{ secrets.REPO_AZURE_DSB_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.REPO_AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.REPO_AZURE_TERRAFORM_USER_SERVICE_PRINCIPAL }}
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  TF_IN_AUTOMATION: true

jobs:
  tf:
    uses: dsb-norge/github-actions-terraform/.github/workflows/terraform-module-ci.yaml@v0
    secrets: inherit
    # if triggered by workflow_run, we only run if the triggering workflow was successful
    if: |
      github.event_name != 'workflow_run' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write # required for checkout action.
      id-token: write # required for Azure password-less login
      pull-requests: write # required for commenting on PR
    with:
      terraform-version: "1.11.x"
      tflint-version: "v0.55.1"
